// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCumcHsZg26gRe2IWKexTXQp-K2xgxDaoY',
    appId: '1:1087498897702:web:9808d27f594d5fe31ed9e7',
    messagingSenderId: '1087498897702',
    projectId: 'spotlight-33al5h',
    authDomain: 'spotlight-33al5h.firebaseapp.com',
    storageBucket: 'spotlight-33al5h.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy35jCa8TVgbJhRFo-6PfXjagt3SQ42Y8',
    appId: '1:1087498897702:android:36e5b353881e55de1ed9e7',
    messagingSenderId: '1087498897702',
    projectId: 'spotlight-33al5h',
    storageBucket: 'spotlight-33al5h.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUx3cDK7eyqY7AmVjXY8SssMO9jhwQN6M',
    appId: '1:1087498897702:ios:26c13fb365f6bb331ed9e7',
    messagingSenderId: '1087498897702',
    projectId: 'spotlight-33al5h',
    storageBucket: 'spotlight-33al5h.firebasestorage.app',
    iosBundleId: 'com.example.spotlightApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUx3cDK7eyqY7AmVjXY8SssMO9jhwQN6M',
    appId: '1:1087498897702:ios:26c13fb365f6bb331ed9e7',
    messagingSenderId: '1087498897702',
    projectId: 'spotlight-33al5h',
    storageBucket: 'spotlight-33al5h.firebasestorage.app',
    iosBundleId: 'com.example.spotlightApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCumcHsZg26gRe2IWKexTXQp-K2xgxDaoY',
    appId: '1:1087498897702:web:d336cf9df04965c61ed9e7',
    messagingSenderId: '1087498897702',
    projectId: 'spotlight-33al5h',
    authDomain: 'spotlight-33al5h.firebaseapp.com',
    storageBucket: 'spotlight-33al5h.firebasestorage.app',
  );
}
